### ISSUE TITLE
Migrate Data to PostgreSQL

### ISSUE THREAD

**Issue by barkincavdaroglu** [ajmcquilkin/meshtastic-emergency-response-client#143]
I predict that data loading will be a bottleneck if we continue using .txt and Python to handle it. It's likely that we would need to store node embeddings of all graphs and then calculate cosine similarity of each node embedding to all others. Storing data in .db and using SQL will make it much faster, especially as the data grows large in size.

PS: Specifying PostgreSQL because it's more powerful than other DMSs especially with its data types (except for presto, but that's overkill).

**Comment by ajmcquilkin** [comment]
Good call, I'm adding the "reach" tag for the time being but as we scale this will definitely become more and more relevant

**Comment by barkincavdaroglu** [comment]
Won't merge since data is being saved as .txt now.
