### ISSUE TITLE
Generate Data

### ISSUE THREAD

**Issue by barkincavdaroglu** [ajmcquilkin/Meshtastic-emergency-response-client#150]
In relation to Tim's [remark](https://github.com/dartmouth-cs98/project-22f-meshtastic/issues/42#issuecomment-1325806610), we need to generate data for performance rating of algorithms and training of the ML model. We might need to get more devices to mimic the number of rescuers in real life.

**Comment by sherry1iu** [comment]
Hey @barkincavdaroglu do you want to make this issue on the other repo? based on Tim's comments

**Comment by barkincavdaroglu** [comment]
This won't be possible. Closing.
