### ISSUE TITLE
Personal Goals

### ISSUE THREAD

**Issue by samfydega** [ajmcquilkin/Meshtastic-emergency-response-client#158]
# Sam Crombie | Personal Goals
*What does success for this class mean to you?*

* I get comfortable with full-stack development where I am able to stand up a new project with minimal friction.
* I build a strong working proficiency of Typescript and Redux to apply to future projects I work on.
* The Meshtastic Team gets to conduct a field test of our client with the NH volunteer rescue team we've been working with.
* Our emergency client contribution continues to be worked on by the open source community after the term ends.
* I earn the respect and admiration of Tim and Natalie.

## Challenges
*What are some challenges you foresee?*

* I anticipate that we will face a challenge effectively scoping sprints throughout the term, specifically scoping them enough to where we can achieve enough progress each week.
* I believe it will be challenging to get the product to a point where we are comfortable conducting a field test with a volunteer team. This outcome, which is the ideal, is a very high bar.
* Building on the last challenge, I believe it will be difficult getting the client stable and compatible across platforms, which may limit our ability to test in the field.

**Comment by ajmcquilkin** [comment]
@samfydega This should be on the fork lol

**Comment by nataliesvoboda** [comment]
Hi Sam, A field test - wow yes that would be wonderful. I wonder if you could break this down into smaller goals in case the "high bar" doesn't work out. Could this test be just on campus with your team?
