### ISSUE TITLE
[Part 2] Apply Mock Edges to Real-Time Graph

### ISSUE THREAD

**Issue by uhuruhashimoto** [ajmcquilkin/meshtastic-emergency-response-client#209]
Mocks will be useful to test the display if we generate random edges. So adapt the existing mocks to generate random edges for an existing hashmap of nodes/locations.

There may be a follow-up ticket to deal with this data (passing it to the frontend).

**Comment by barkincavdaroglu** [comment]
Take a look at random geometric graphs. Could be useful for generating mock data that would be somewhat similar to real data.
