### ISSUE TITLE
[sprint] Sprint 2 Retro

### ISSUE THREAD

**Issue by uhuruhashimoto** [ajmcquilkin/Meshtastic-emergency-response-client#24]

**Comment by ajmcquilkin** [comment]
This is against the wrong repo, just for future reference. This isn't relevant to product development

**Comment by timofei7** [comment]
i changed the default repo to the project one.  would prefer if all repos resided in the dartmouth-98 org generally so we can see and analyze them - can always push to others to keep them in sync.

**Comment by timofei7** [comment]
closing this now

**Comment by timofei7** [comment]
actually i don't have permissions  on this repo. please close this stuff
