### ISSUE TITLE
Add ability to define meshtstic port via command line option

### ISSUE THREAD

**Issue by D4rk4** [ajmcquilkin/meshtastic-emergency-response-client#299]
Nice to have the ability to define mehtastic device port via the command line option.
Why?
- Application used by not technically trained user => sysop may define port in shortcut/shell script.
- Application running automatically when OS booted up and ready to action (kiosk mode)

**Comment by ajmcquilkin** [comment]
That's an interesting idea, I'd love to see this!

What do you think should happen if a CLI argument was used to launch the application (maybe `--port SOME_PORT`) and connection on that port failed? Would you want the application to start normally or would you want the launch to fail?

**Comment by D4rk4** [comment]
Better for UX just show a warning, and continue.

**Comment by ajmcquilkin** [comment]
Update on this -- I've tried to tackle this ticket a couple of times, but it seems like Tauri is failing to parse CLI arguments when in development mode. Might need to hold off on this ticket for the time being, although this is absolutely something I want to get into the application. Also happy to accept contributions on this if anyone has experience with running Tauri with CLI args. 

This is the guide I've been working with: https://tauri.app/v1/guides/features/cli/

**Comment by ajmcquilkin** [comment]
Update on this issue -- the solution I've found is to only test the CLI using the `pnpm run rust:build` command then running the built executable from there (`EXECUTABLE_PATH --port PORT_LOCATION`). There's still some UI issues, but there's functional code on the [cli-port-connection](https://github.com/ajmcquilkin/meshtastic-emergency-response-client/tree/ajmcquilkin/cli-port-connection) branch.

**Comment by D4rk4** [comment]
When run with --port COM4, I see port pick dialog, butin logs I observe communication messages with MCU. UI in master still not handle it?

**Comment by ajmcquilkin** [comment]
Let me push an update to the CLI features, I think a regression snuck into the code.

**Comment by ajmcquilkin** [comment]
Just pushed an update that 1) allows for running the CLI arguments with the `pnpm run rust:dev` command, and 2) that removes an error within the UI code that occasionally caused the UI to miss the "device configured" event

**Comment by D4rk4** [comment]
Working!
