### ISSUE TITLE
Modulo direction by 360

### ISSUE THREAD

**Issue by sherry1iu** [ajmcquilkin/meshtastic-emergency-response-client#305]
![image.png](https://images.zenhubusercontent.com/634862f65743a1e6f29fb15d/f60d98a5-7a6a-4443-adeb-0f32f4947c59)

**Comment by ajmcquilkin** [comment]
Is this not a bug in the firmware? I feel like this isn't necessarily an issue with our program

**Comment by sherry1iu** [comment]
I think so? but we're also displaying the node rotated by a few million degrees, so I feel like we should be consistent
