### ISSUE TITLE
[Bug] No handling for waypoints in ChannelMessagePacket

### ISSUE THREAD

**Issue by sherry1iu** [ajmcquilkin/meshtastic-emergency-response-client#312]
Clicking the 'messages' tab after sending waypoints throws an error

**Comment by sherry1iu** [comment]
Closed; brainfart sorré

**Comment by sherry1iu** [comment]
![image.png](https://images.zenhubusercontent.com/634862f65743a1e6f29fb15d/1cc5fe1c-9144-4ace-bc73-7b41b522ba7c)

Right now, the `ChannelMessagePayload` type only has the ability to handle text.

**Comment by ajmcquilkin** [comment]
I had to remove the waypoint portion of the type to make the messaging page work, you should be go to union the existing type with `{ waypoint: WaypointPacket }`.
