### ISSUE TITLE
Create Dummy Search Component

### ISSUE THREAD

**Issue by ajmcquilkin** [ajmcquilkin/Meshtastic-emergency-response-client#36]
Create a UI-consistent but non-functional search bar and options button. This bar and button should be placed correctly and properly styled.

![image.png](https://images.zenhubusercontent.com/5cbded9dbb49680760c0ee99/559ea7a6-c85d-4f5e-92e4-7bb7deb93678)

**Comment by samfydega** [comment]
:(
