### ISSUE TITLE
Petgraph's update edge doesn't factor in parallel edges

### ISSUE THREAD

**Issue by barkincavdaroglu** [ajmcquilkin/meshtastic-emergency-response-client#68]
https://github.com/petgraph/petgraph/issues/520

Consider the following:
```rust
let mut G = Graph::new();

let u: String = "u".to_string();
let v: String = "v".to_string();

let u_idx = G.add_node(u.clone());
let v_idx = G.add_node(v.clone());

G.add_edge(u.clone(), v.clone(), 1 as f64);
G.add_edge(u.clone(), v.clone(), 2 as f64);
```

Printing the edges, we get:
```
Edge { u: NodeIndex(0), v: NodeIndex(1), weight: 1.0 }
Edge { u: NodeIndex(0), v: NodeIndex(1), weight: 2.0 }
```
which is expected. Now let's say we want to update the first edge we added, the one with weight 1.0:

```rust
G.update_edge(u.clone(), v.clone(), 11 as f64, Some(0), None);
```

Printing the edges, we get:
```
Edge { u: NodeIndex(0), v: NodeIndex(1), weight: 1.0 }
Edge { u: NodeIndex(0), v: NodeIndex(1), weight: 11.0 }
```

This is not correct. We wanted to update the first edge but the last added edge is updated per petgraph's update_edge function.

**Comment by insideoutclub** [comment]
https://github.com/petgraph/petgraph/issues/520#issuecomment-1428931602
